robotframework/RIDE

pavement.py
=> Fix download URL in metadata

src/robotide/editor/grid.py, src/robotide/editor/gridcolorizer.py, src/robotide/editor/kweditor.py, src/robotide/editor/texteditor.py, src/robotide/preferences/__init__.py, src/robotide/preferences/colors.py, src/robotide/preferences/editor.py, src/robotide/preferences/editors.py, src/robotide/preferences/saving.py, src/robotide/preferences/settings.cfg, src/robotide/preferences/settings.py, src/robotide/publish/messages.py, src/robotide/ui/mainframe.py, utest/editor/test_gridcolorizer.py, utest/settings/test_settings.py
- Re-organize editor related settings in config file. 
- Add setting for auto adjusting grid column width, and related settings col size and max col size
- Add config option for using monospace font face in grid
- Apply font face, font size and color setting changes immediately in grid editor
- Fixes #1455, #1449, #1401, and #1162
=> Preferences improvements

src/robotide/recentfiles/recentfiles.py
=> Remove non-existing paths on load/save of recent files

src/robotide/namespace/resourcefactory.py
=> Normalize file name for cache *after* creating it

src/robotide/contrib/testrunner/runprofiles.py
This also fixes #1317 for good.
=> Fix false reporting of missing RF installation

src/robotide/ui/filedialogs.py, src/robotide/ui/mainframe.py, src/robotide/ui/treenodehandlers.py
Also removed the duplication between opening suites and opening resource
files
=> Use default file format as default wildcard

src/robotide/preferences/editor.py
For some reason, closing the preferences dialog causes a number of
tree selection events to be triggered. Ignore those, since handling
those might cause PyDeadObjectErrors
=> Fix errors in preferences dialog closing on Windows

src/robotide/__init__.py
It's unlikely there will be more 2.8.12.X releases anyway
=> Just remove the misleading `newer`

src/robotide/editor/settingeditors.py
=> Fix dead object error in VariablesListEditor

src/robotide/editor/kweditor.py
=> Fix `Find Where Used`

src/robotide/log/log.py
Also remove previous log files on start-up
Fixes #1520
=> Create ride.log with unique identifier

src/robotide/contrib/testrunner/testrunner.py, src/robotide/contrib/testrunner/testrunnerplugin.py, src/robotide/contrib/testrunner/usages.py, utest/contrib/testrunner/test_command_creation.py
-Moved all instances of '--monitorcolors' to '--consolecolors'
-Moved all instances of '--monitorwidth' to '--consolewidth'
'invoke test' passes with no issues reported
=> #1500: Remove deprecated options warning messages

src/robotide/contrib/testrunner/usages.py
Removes the error "option ... not found" and the red color in runner Arguments.
=> Updates arguments for pybot to RF 2.9.1.

src/robotide/validators/__init__.py, utest/validators/test_arguments_validation.py
=> Fix argument validation logic

src/robotide/ui/treenodehandlers.py
=> Tree menu entry: New Dictionary Variable

src/robotide/controller/settingcontrollers.py, src/robotide/editor/settingeditors.py
=> Fix variable name validation and editing

src/robotide/log/log.py
=> Helio guilherme66 fix #1548

src/robotide/ui/tree.py
=> Fzuellich bugfix #1529

src/robotide/__init__.py, src/robotide/log/log.py, utest/resources/__init__.py
Better .format arguments.
Adds wx2.9 without announcing it.
Improves print and text with format().
=> Changes log tab name to 'RIDE Log' and other minor improvements.

src/robotide/controller/macrocontrollers.py, src/robotide/controller/stepcontrollers.py, src/robotide/editor/contentassist.py, src/robotide/editor/robotframeworklexer.py, src/robotide/namespace/namespace.py, utest/controller/test_macro_commands.py, utest/controller/test_occurrences.py, utest/controller/test_stepcontrollers.py, utest/namespace/test_keywords.py, utest/namespace/test_namespace.py
Cleanup code, updated and PEP8 compliant.
Added the 'But' keyword (~~missing in RF?~~).
=> This is a review for PR#17 by @SimonElfvingElekta dated nov. 2013.

src/robotide/ui/tree.py
Changed almost all of the tree.py code to be PEP8 compliant (except the method `_create_node`, but I guess it is more readable like this).
=> Changed code to be PEP8 compliant and removed unnecessary method

src/robotide/ui/pluginmanager.py
=> Fixes #1576.

src/robotide/editor/kweditor.py, src/robotide/utils/variablematcher.py
Not possible to show '&' in dictionary variables wx.RadioBox. (but possible with wx.RadioButton, see https://github.com/wxWidgets/Phoenix/issues/39 )
(includes PEP8 changes)
=> Fix finding usages of variables (#1605).

src/robotide/controller/settingcontrollers.py, src/robotide/controller/tags.py
=> View all tags: fix delete functionality

src/robotide/ui/tagdialogs.py
The View All Tags dialog would not show if there are Tags with unicode characters. This PR fixes this.
=> Fixes viewalltags dialog to show tags with unicode characters.

src/robotide/contrib/testrunner/testrunnerplugin.py
=> Confirmation dialog when pressing start without tests selected

src/robotide/editor/cellrenderer.py, src/robotide/editor/contentassist.py.orig, src/robotide/editor/fieldeditors.py, src/robotide/editor/gridbase.py, src/robotide/editor/kweditor.py, src/robotide/editor/kweditor.py.orig, src/robotide/preferences/editor.py, src/robotide/preferences/editors.py, src/robotide/preferences/settings.cfg
created cell renderer for managing size of cells in grid editor.
The values in preferences/grid now apply
Please check if the proposed behaviour is according your expectation
=> fix cells size in Grid editor

requirements.txt, requirements_win32.txt, setup.py, src/robotide/controller/project.py, src/robotide/editor/customsourceeditor.py, src/robotide/ui/actiontriggers.py, src/robotide/ui/mainframe.py
Fixes #1793 
This fix adds the PyWin32 dependency only when installing in Windows.
=> Installer - Fixes installation to all OS

.whitesource, src/robotide/postinstall/desktopshortcut.py
Removed the tab, because was crashing on Linux.
=> Desktopshortcut removal of GUI

.whitesource, src/robotide/contrib/testrunner/TestRunnerAgent.py
It would enter in PAUSE on all next steps.
Fixes #1812
=> Fixes Commented cells with # on Pause parsing

src/robotide/contrib/testrunner/TestRunnerAgent.py, src/robotide/contrib/testrunner/runprofiles.py, src/robotide/contrib/testrunner/testrunner.py, src/robotide/contrib/testrunner/testrunnerplugin.py
=> Changes encoding. Fixes running chinese path in python2.7 under Windows

src/robotide/editor/tags.py
Added platform check, so that event is skipped only on linux.
=> Fix for ticket #1888

src/robotide/editor/__init__.py
=> Fix issue  #1857: Duplicate save button

src/robotide/editor/__init__.py, src/robotide/editor/texteditor.py
This feature wasn't broken, it was missing altogether.
=> Fixes issue #1919: Text editor update

src/robotide/controller/filecontrollers.py, src/robotide/controller/settingcontrollers.py, src/robotide/editor/__init__.py, src/robotide/lib/robot/libdocpkg/htmlwriter.py, src/robotide/lib/robot/parsing/populators.py, src/robotide/lib/robot/running/builder.py, src/robotide/lib/robot/writer/datafilewriter.py, src/robotide/preferences/saving.py, src/robotide/ui/filedialogs.py, src/robotide/ui/mainframe.py
It's ugly, but it works. I think... please test it.
There's also some unrelated changes. I removed a few duplicate functions from filecontrollers.
Resource option will only appear if you try to `Change Format` of resources or create a `New Resource`
=> Fixes issue #1909: Added support for Resource filetype

src/robotide/contrib/testrunner/testrunnerplugin.py, src/robotide/editor/texteditor.py, src/robotide/preferences/editors.py, src/robotide/preferences/settings.cfg
I hope I didn't break anything...
=> Made some improvements to fix from issue #1905

src/robotide/controller/robotdata.py
I experimented with adding `*** Settings ***` and `*** Keywords ***` too, but I didn't see any use for them (other than making this PR more complicated).
Please check out the PR and tell me how you want to proceed.
Fixes #1832
=> Fixes #1832:  Added default template for when new suite is created

src/robotide/editor/cellrenderer.py, src/robotide/editor/kweditor.py, src/robotide/preferences/settings.cfg
This PR is still a work in progress. I need you to test its robustness.
If you want to release a new version, then please make sure this PR is merged.
Major fixes:
- grid now resizes when doing stuff if autosize option is checked
- made empty column to shrink only if autosize option is checked
- added minimum width and height
etc
=> Fixes some Grid resize issues

src/robotide/ui/tree.py
Modified OnTreeItemCollapsing to be less recursive.
Fixes #1958
=> Fixes #1958: Modified OnTreeItemCollapsing to be less recursive

src/robotide/context/coreplugins.py, src/robotide/context/logger.py, src/robotide/parserlog/__init__.py, src/robotide/parserlog/parserlog.py, src/robotide/publish/messages2.py, src/robotide/publish/messages3.py, src/robotide/ui/notebook.py
There is no dialog when there are deprecated file formats or errors when loading Test Suites.
=> New Parser Log tab to avoid dialog when loading Test Suite

src/robotide/context/coreplugins.py, src/robotide/context/logger.py, src/robotide/parserlog/__init__.py, src/robotide/parserlog/parserlog.py, src/robotide/publish/messages2.py, src/robotide/publish/messages3.py, src/robotide/ui/mainframe.py, src/robotide/ui/notebook.py, test_all.sh
If not valid robotframework files it will open in Code Editor.
Files can also be open with double-click.
TODO: Context menu with more options.
=> Open Files or Directories in RIDE with right-click from Files panel

src/robotide/editor/contentassist.py, src/robotide/editor/kweditor.py
=> Change to setFocus on Windows 10

src/robotide/editor/texteditor.py
Removed the delete function from texteditor. Should be tested on Windows and MacOS.
=> Fixes #1367

src/robotide/editor/texteditor.py
Instead of writing the TAB char code, it types the number of spaces in Preferences->Save setting.
Pressing Shift-Tab moves to the left the corresponding number of spaces, and if Control is pressed text is selected,
=> Change TAB to add spaces in Text Editor

src/robotide/contrib/testrunner/TestRunnerAgent.py
=> TestRunnerAgent: Fall back to pickle if JSON fails

src/robotide/editor/texteditor.py
I'll leave the testing to you ;)
=> #2006 Removed event skip from autocomplete in Text Editor

src/robotide/editor/texteditor.py
This fixes code completion on Grid Editor, and updating when moving from Text Editor to Grid.
=> Added save when changing from Text Edit

src/robotide/contrib/testrunner/runprofiles.py
=> Fix runner args

src/robotide/controller/ctrlcommands.py, src/robotide/controller/macrocontrollers.py, src/robotide/controller/ui/treecontroller.py, src/robotide/publish/messages2.py, src/robotide/publish/messages3.py
=> Fixed running of unselected test case

src/robotide/editor/texteditor.py
Fixes #2034
Added solution provided by [raykudryavka123](https://github.com/raykudryavka123). I tested it and found no issues.
=> Fixed Text Editor search bug

src/robotide/ui/mainframe.py
=> Forces Layout Direction to be Left To Right.

src/robotide/editor/texteditor.py
I've added back the code I removed and modified `is_focused` because it wasn't returning the correct open tab and thus causing caret position to not be set.
=> Fixed focus issue introduced by Cursor pos merge

src/robotide/application/application.py, src/robotide/application/updatenotifier.py, src/robotide/context/logger.py, src/robotide/editor/editordialogs.py, src/robotide/editor/popupwindow.py, src/robotide/preferences/editor.py, src/robotide/preferences/excludes.py, src/robotide/run/configmanagerui.py, src/robotide/searchtests/dialogsearchtests.py, src/robotide/ui/filedialogs.py, src/robotide/ui/keywordsearch.py, src/robotide/ui/mainframe.py, src/robotide/ui/resourcedialogs.py, src/robotide/ui/review.py, src/robotide/ui/tagdialogs.py, src/robotide/usages/usagesdialog.py, src/robotide/widgets/dialog.py
=> Forces Layout Direction to be Left To Right, and language English.

src/robotide/editor/kweditor.py, src/robotide/preferences/editors.py
Not perfect but enough.
If activate/deactivate Fixed Font, the list of fonts will only be updated on next RIDE restart.
=> Activates Font Face change to Grid Editor (Segoe UI Symbol, fix Emojis)

src/robotide/log/log.py
=> Changes log to use unicode when on Python 2.7

src/robotide/editor/kweditor.py
This reverts commit b7336e0020f456a8c621c602aacd2736c7063f92.
=> Revert "Fixed SelectAll issue in Grid Editor (#2096)"

src/robotide/editor/texteditor.py
Includes missing fix for #2102
=> Corrects text update when on read-only on Text Editor

src/robotide/editor/contentassist.py, src/robotide/lib/robot/parsing/model.py, src/robotide/spec/iteminfo.py, utest/spec/test_iteminfo.py
=> Fix #2107 - Avoids changes in Resource file name when content assist.

.travis.yml, utest/ui/test_tagdialogs.py
For now removes the installation of RIDE because it is not needed to run unit tests.
=> Fix travis

src/robotide/contrib/testrunner/runprofiles.py
=> Fixes reprocessing of %date% %time% variables on Windows

src/robotide/contrib/testrunner/runprofiles.py, src/robotide/controller/validators.py, utest/contrib/testrunner/test_process.py, utest/contrib/testrunner/test_pybot_arguments_validation.py, utest/controller/test_file_rename.py, utest/controller/test_filecontrollers.py, utest/controller/test_for_loop.py, utest/controller/test_modifications_on_disk.py, utest/ui/test_tagdialogs.py, utest/ui/test_tree.py
=> Cleans up unittests

src/robotide/context/logger.py, src/robotide/editor/contentassist.py, src/robotide/editor/fieldeditors.py, src/robotide/editor/kweditor.py, src/robotide/editor/settingeditors.py, src/robotide/editor/tags.py, src/robotide/log/log.py, src/robotide/parserlog/parserlog.py, src/robotide/preferences/excludes.py, src/robotide/searchtests/dialogsearchtests.py, src/robotide/ui/preview.py, src/robotide/widgets/text.py
Now selected text is correctly highlighted on Windows.
=> Fixes select text

src/robotide/context/__init__.py, src/robotide/editor/contentassist.py, src/robotide/editor/texteditor.py
symbols. 
Adds support for Ctrl-3 and Ctrl-4 (Comment/Uncomment)
=> Text Editor - Encloses text in Cell or selected text with certain

src/robotide/editor/contentassist.py, src/robotide/editor/kweditor.py
=> Fixes selection in keywords list suggestion

src/robotide/editor/texteditor.py
=> Implement auto tab

src/robotide/ui/mainframe.py
=> Adds ! to Save item on menu. Not detected when removed.

src/robotide/ui/filedialogs.py, src/robotide/widgets/dialog.py
Fixes wx.ALIGN in vertical or horizontal boxes.
=> Upgrade wxPython to 4.1.0

src/robotide/contrib/testrunner/runprofiles.py, src/robotide/log/log.py, src/robotide/parserlog/parserlog.py, utest/contrib/testrunner/test_process.py
=> Log misc fixes

src/robotide/log/log.py, src/robotide/parserlog/parserlog.py
=> Better error and removal of old log files.

src/robotide/lib/robot/parsing/htmlreader.py
Should not show this warning message if there're report/log html file in the workspace.
=> Fix parsing warning of report/ log html file

src/robotide/context/__init__.py, src/robotide/preferences/__init__.py, src/robotide/preferences/widgets.py
Tested on Mac, Windows, and Linux(Ubuntu 20.04).
=> Bug fixing on perference panel

src/robotide/lib/robot/running/dynamicmethods.py, src/robotide/lib/robot/utils/__init__.py, src/robotide/lib/robot/utils/robottypes.py, src/robotide/lib/robot/utils/robottypes2.py, src/robotide/lib/robot/utils/robottypes3.py, src/robotide/spec/xmlreaders.py
=> Fix dynamic doc

src/robotide/namespace/resourcefactory.py
https://github.com/robotframework/RIDE/issues/2108
=> Fixed issue#2108:

src/robotide/ui/treeplugin.py
=> Fixed error occurring when deleting test cases

CHANGELOG.adoc, src/robotide/contrib/testrunner/testrunnerplugin.py, src/robotide/controller/ui/treecontroller.py, src/robotide/editor/contentassist.py, src/robotide/ui/treeplugin.py
- Fixed some log message issue
- Fixed issue 2159
- Fixed a invalid cases selection issue
here's the reproduce step:
1. select one case, and run
2. go to text edit and apply some changes
3. the case will become unchecked
4. click run, you'll find that case is still selected
=> Fix issue 2159

src/robotide/postinstall/__main__.py
This is the merge for the original PR:
Fix broken mac os post install #2262
By @jnhyperion
=> Post install fix

CHANGELOG.adoc, src/robotide/editor/contentassist.py, src/robotide/editor/kweditor.py
=> Fixes Pressing Del delete cell content on Cell Editor

src/robotide/controller/ctrlcommands.py, src/robotide/controller/settingcontrollers.py, src/robotide/editor/gridbase.py, src/robotide/editor/kweditor.py
=> Added whitespace unescape to grid and documentation; Optimized OnKeyDown structure

CHANGELOG.adoc, src/robotide/context/__init__.py, src/robotide/controller/filecontrollers.py, src/robotide/editor/editors.py, src/robotide/editor/settingeditors.py, src/robotide/namespace/resourcefactory.py, src/robotide/ui/treeplugin.py
- Fixed resource file will disappear after saving from Text Editor
- Fixed duplicated resource file/folder in tree nodes
[TestCases.zip](https://github.com/robotframework/RIDE/files/5149027/TestCases.zip)
=> Fix resource import path issue

CHANGELOG.adoc, src/robotide/controller/ctrlcommands.py, src/robotide/controller/filecontrollers.py, src/robotide/controller/settingcontrollers.py, src/robotide/controller/tablecontrollers.py, src/robotide/ui/treenodehandlers.py, utest/controller/test_controllers.py, utest/controller/test_filecontrollers.py
In addition to that, I also added Move Up and Move Down to variable tree menu.
=> Implemented "Sort Variables" and "Sort Tests" functionalities in tree menu

tasks.py, utest/controller/test_chiefcontroller.py, utest/controller/test_controllers.py, utest/resources/mocks.py
Fix unit test failures in windows
=> Fix unit test failures in windows

CHANGELOG.adoc, src/robotide/application/application.py, src/robotide/controller/project.py, src/robotide/utils/eventhandler.py, utest/resources/robotdata/imports/testsuite.txt
=> Improve file system changes detection

CHANGELOG.adoc, src/robotide/editor/kweditor.py
=> Fix JSON editor not saving nor validating JSON.

.appveyor.yml, src/robotide/context/__init__.py, src/robotide/editor/texteditor.py
CTRL-I new row in Text editor (updated code by Hélio)
=> Texteditor ctrl i

CHANGELOG.adoc, src/robotide/controller/settingcontrollers.py, utest/controller/base_command_test.py, utest/controller/test_rename_keywords.py, utest/resources/datafilereader.py, utest/resources/robotdata/complex_tests/TestSuite.robot
=> Improve rename

CHANGELOG.adoc, src/robotide/editor/texteditor.py, utest/editor/test_texteditor.py
Fix position of cursor and words detection in get_selected_or_near_tex_
=> Misc fixes

src/robotide/controller/filecontrollers.py
Quick fix for launching in Windows.
=> Fix launcher in Windows. Tested with https://freecommander.com/

src/robotide/ui/treenodehandlers.py
=> Fix missing context menu items in Keywords in Tree

src/robotide/application/releasenotes.py, src/robotide/editor/kweditor.py, src/robotide/editor/texteditor.py, src/robotide/lib/robot/parsing/datarow.py, src/robotide/lib/robot/parsing/tablepopulators.py, src/robotide/lib/robot/writer/filewriters.py, src/robotide/lib/robot/writer/rowsplitter.py
=> Fixes continuation inside blocks and CTRL-X in Grid Editor
