src/robotide/application/application.py
src/robotide/contrib/testrunner/testrunnerplugin.py
src/robotide/controller/project.py
src/robotide/preferences/__init__.py
src/robotide/preferences/settings.py
src/robotide/run/process.py
utest/controller/test_backup.py
utest/preferences/test_settings.py
utest/resources/mocks.py
utest/run/test_process.py
utest/settings/test_settings.py

This means mostly removing from __future__ import with_statement.
Even previous versions have not been fully 2.5 compatible, so this
is just removing dead code.

Remove Python 2.5 compatibility

---

src/robotide/editor/tags.py

This is required in OSX, otherwise the tag box height is calculated wrong
initially.

Set min height to tag box

---

src/robotide/ui/tagdialogs.py

Since tags are case insensitive in RF, the search dialog also needs to handle
tags case insensitively.

Fix normalization of tag names in View All Tags

---

src/robotide/spec/specimporter.py
src/robotide/ui/filedialogs.py
src/robotide/ui/mainframe.py

In OSX, spaces in between | and wildcard definition cause
the defintion not to work. Also did some cleanup
Fixes #1457

Fix wildcards used in file open dialogs.

---

src/robotide/namespace/namespace.py
src/robotide/spec/remote/Remote.py
utest/datafilereader.py
utest/namespace/test_pythonpath_setting.py
utest/resources/mocks.py

When using installed RF libraries, it is still required to have
`Remote` in PYTHONPATH, because remote library keywords cannot
be known statically. The easiest way to do this is to have `Remote.py`
put separately in the PYTHONPATH.

Fix Remote imports with system RF libs

---

src/robotide/controller/tags.py
src/robotide/namespace/namespace.py
src/robotide/spec/librarymanager.py
utest/namespace/test_namespace.py

It seems that str.format() breaks with UnicodeEncodeError if
str is ascii literal and format arguments are unciode. Fix all usages
of `format` to prevent runtime errors

Fix UnicodeEncodeErrors in `str.format()` usages

---

AUTHORS.txt
src/robotide/ui/tagdialogs.py

I don't know how to work 'view all tags' with execute '_search_for_tags()' in tagdialogs.py without 'set()' in 'normalizing.py'.
But after I noticed that function replaced to '__setitem__' I could fix this problem.

fix view all tags(F7) doesn't work on windows #1526

---

setup.py

now the HTML message is correctly shown. Fixes #1549.

Fixes installation when Robot Framework is not installed,

---

src/robotide/log/log.py

Outputs caught exception to allow the user taking action,
(there is a locked file that RIDE cannot remove)

Fixes #1539, by adding exception handling when in Windows.

---

src/robotide/contrib/testrunner/testrunnerplugin.py

Changed font designation from SYS_SYSTEM_FIXED_FONT to SYS_ANSI_FIXED_FONT. SYS_SYSTEM_FIXED_FONT creates a truly bugly experience. SYS_ANSI_FIXED_FONT isn't perfect, but it's a bit more tolerable.

Make test runner console font less ugly

---

src/robotide/ui/tagdialogs.py

Implemented enhancement #1527: "Tag list sort by name in View all tags".
Added the `mixin wx.lib.mixins.listctrl.ColumnSorterMixin` that is implemented by `robotide.ui.tagdialogs.ViewAllTagsDialog`. This includes the creation of a new field `itemDataMap` and `sort_state` as well as a call to `self._tags_list.SetItemData` in `self._execute`.
The second commit ensures that the sort order is kept on refresh.

Enhancement #1527 sort tag list

---

src/robotide/controller/ui/treecontroller.py
src/robotide/ui/tree.py
utest/controller/ui/test_treecontroller.py

Fixing #1416 by removing call to `TreeSelectionController.unselect_all` after files change. As a consequence implementing a call to deselect nodes that are removed and thus maintaining a consistent model of selected tests. As far as I am aware of, no undo operation is provided for removed TestCases (at least none working on my local installation) and therefore did not need to be considered. A simple unit test is added to ensure new method in `TreeSelectionController` works as expected.
Also merged latest PEP8 related changes from master.

Bugfix #1416: test case checkbox cleard upon save in textedit

---

src/robotide/application/pluginconnector.py

In RF 2.9, Robot Framework's get_error_details method was updated to
return a tuple with message and traceback.
This fixes issue #1598.

Update BrokenPlugin to RF 2.9's get_error_details method

---

src/robotide/controller/commands.py
utest/controller/test_rename_keywords.py

There is a known bug. This is the comment in code:
-# When we change non-gherkin to gherkin, the keyword changes too.
-# The workaround is not to Rename keyword, but only edit field.

Fixes #1556, by ignoring starting Gherkin keywords.

---

src/robotide/__init__.py

Uses print function.
Replaces wx.PySimpleApp by wx.App to avoid future deprecation.
(Code is PEP8 compliant)

Adds --version option to RIDE.

---

src/robotide/controller/commands.py
src/robotide/controller/filecontrollers.py
src/robotide/ui/treenodehandlers.py

- for remove read only attribute (I think its cross plattfrom, but only
tested on win 7 x64)
-> could be improved the be active only on read only files
- for open containing folder ( only working on win32, , but only tested
on win 7 x64)

Added context menu items

---

requirements.txt
setup.py
src/bin/ride_postinstall.py
src/robotide/postinstall/__init__.py
src/robotide/postinstall/__main__.py
src/robotide/postinstall/desktopshortcut.py

Removes distutils use. Fixes  #1582.
Corrected windows detection, and arguments for post_install.
Create a Desktop shortcut to Linux script starting RIDE.
This is a minimal solution to have shortcut in Mac OS X.
Calls ride_postinstall.py after install.
Added ride_postinstall to run after setup.py or pip.
Now ride_postinstall can be run standalone in all operative systems.
Asks to create Desktop shortcut in Windows.
Introduces a new dependency pywin32 (packages only from sourceforge).
Fixed user detection on installs with "sudo".
ride_postinstall.py is not compatible with Python 2.6.
Fix for linux desktop directory not localized.
Corrected shebang in ride.py.
Transformed ride_postinstall.py into a module. Tested in Linux: Ubuntu,
Fedora, CentOS, OpenSUSE.
To run: python -m …

Creates desktop shortcuts for all platforms.

---

src/robotide/contrib/testrunner/testrunnerplugin.py
src/robotide/editor/contentassist.py
src/robotide/editor/kweditor.py
src/robotide/editor/popupwindow.py
src/robotide/editor/tooltips.py

some fixes on grid editor:
- content assist when cancelled by ESC return correct value
- when content assist is invoked the existing contents is not cleared
- holding ctrl and hover over keyword show its information (the ctrl + M keyword is also working for backward compatibility )
- tooltips is no longer shown on other (wrong) tabs
- some idle event crashes fix.

Grid editor fixes

---

src/robotide/controller/project.py
src/robotide/editor/customsourceeditor.py
src/robotide/ui/actiontriggers.py
src/robotide/ui/mainframe.py

The file manager allows to open in RIDE files with supported file format (`.robot`, `.txt`, `.tsv`, `.html`).
If the format is invalid (not a Robot Framework file), a message is shown and the file opens in the new Source Editor (still under development).
Any other format will open in the Source Editor.
File are opened by double-clicking on them.
After opening a test suite, the file explorer updates to the selected file.

Add a file explorer

---

src/robotide/preferences/editor.py
src/robotide/preferences/editors.py

I also did a few other changes:
- Increased the window size by 10 because one of the labels was very close to the margin
- Added color setting for 'Unknown Variable Foreground' because it was missing
- Moved the column for background colors first because it has more elements, otherwise the column for foreground colors would have left a big gap between it and the reset button

 Fixes issue #1904: Reset colors button

---

src/robotide/editor/__init__.py
src/robotide/editor/kweditor.py
src/robotide/editor/listeditor.py
src/robotide/editor/settingeditors.py
src/robotide/publish/messages2.py
src/robotide/publish/messages3.py
src/robotide/ui/mainframe.py
src/robotide/ui/tree.py
src/robotide/utils/eventhandler.py
src/robotide/utils/noconflict.py

The issue was present only on python 3. It was occurring because implemetation for metaclass was changed in python 3. As such, a special solution was needed to be both python 2 and python 3 compatible.

Fixes issue #1912: Metaclass compatibility

---

src/robotide/controller/validators.py
src/robotide/ui/tree.py

This is an attempt at fixing Validation error which appears when renaming suites\resources. This should also fix the crash that was reported by several tickets.
#1906, #1895, #1823, #1822
How to reproduce the crash on python 3, Windows 10:
1) rename a label and remove all characters
2) click somewhere else in gui
3) after validation error pops up, click ok (following this ride crashes)
Please verify this on MacOS too.

Validation error fix

---

src/robotide/editor/tags.py
src/robotide/preferences/widgets.py

On linux (with gtk3) some sizes needed to be bigger.
In PR #1905 I made a factor related to this smaller, so on linux not all text was being shown.

Conditioned sizes of Tagboxes and ComboBoxes to be platform specific

---

src/robotide/controller/filecontrollers.py

Filename value needed to be initialized, so that RIDE uses the file's path (instead of the directory path).
Fixes #1869 and #1818.

Fixes permission issue

---

src/robotide/ui/tree.py

Fixes new issue introduced in previous PR #1959 that fixed #1958. Animation should now get hidden no matter from where you collapse the tree.

Modified OnTreeItemCollapsing to be more recursive

---

src/robotide/editor/kweditor.py
src/robotide/editor/texteditor.py

I've set it so that `TextEditor` shortcuts are unregistered if tab is not selected.
I've also fixed a small issue that I noticed in kweditor.

#1878 Fixes conflict generated by TextEditor shortcuts

---

src/robotide/ui/tree.py

When `_set_icon_from_execution_results()` is called it sets item window to `AnimationCtrl()`, but it isn't deleted after `AnimationCtrl()` is destroyed. This was causing an error when moving test in tree.

#2009 Fixes tests getting remove from tree when moving them

---

src/robotide/editor/texteditor.py

Steps to reproduce issue:
1. Type a keyword start in Text Editor and press Ctrl-Space, select from list
2. Go to Grid Editor, and Ctrl-Space and select from list with Arrow-down and then Enter,
3. The keyword is not saved to cell, and there is a redraw of the Grid.

Fixes keyword autocompletion in Text Editor

---

src/robotide/editor/texteditor.py
src/robotide/preferences/editors.py

Fixes issue #2027
Additionally, I've also modified preferences dialog for Text Editor so that unavailable colorization settings are not added when `Pygments` is not installed.

Separated colorization and font dependency on Pygments in Text Editor

---

src/robotide/searchtests/dialogsearchtests.py

When you open it there is a black square on the search box.
Also, if you click on the listctrl when there are no results an error occurs (RIDE can sometimes even crash from this).

Fixed some really old issues in testsearch dialog

---

src/robotide/editor/cellrenderer.py

Issue originates from `_wordwrap()`. The line `pte = dc.GetPartialTextExtents(line)` returns a list of values, where each value represents an emoji. For emoji it returns 2 values instead of one, so it throws an index error when the line is parsed character by character.
Fixed emojis for issue #2043

Fixed emoji index error

---

src/robotide/log/log.py
src/robotide/parserlog/parserlog.py

When starting RIDE this error appears:
`RuntimeError: wrapped C/C++ object of type TagsDisplay has been deleted`
It was first mentioned [here](https://github.com/robotframework/RIDE/issues/2039#issuecomment-550014579) in issue #2039
This issue was introduced by commit from PR #1977. There, I also mentioned another issue, related to charmap encoding. I've fixed that too.

Fixed runtime error

---

src/robotide/parserlog/parserlog.py

When starting RIDE this error appears:
`RuntimeError: wrapped C/C++ object of type TagsDisplay has been deleted`
It was first mentioned here in issue #2039
Error occurs because RIDE tries to show Parser Log tab at startup.
To fix it I added a second condition to `OnViewLog()`, so that Parser Log tab is only shown when the user selects from Menu.
The `show_tab` call at line 122 should remain removed.

Fixed runtime error again

---

src/robotide/editor/gridcolorizer.py

I reverted `_coloring_task` and `colorize` to an older implementation where recursion error doesn't occur. More specifically, to [before this commit](https://github.com/robotframework/RIDE/commit/de18d56457490ef30857c0efc26ca5e4d1133766).
I haven't seen any issues, but I might have missed something. Please pay attention when testing this.

Fixed colorization error in large test cases

---

src/robotide/ui/tree.py

I think it would be better if we remove this, since it doesn't work very well. 
If you try to edit a test case while the ellipsize is visible, the horizontal scrollbar from tree will move and cause ellipsize position to be calculated incorrectly for all labels.
It's a [wx bug](https://github.com/wxWidgets/Phoenix/issues/1395), so we can't do anything about it.

Removed ellipsize from tree

---

src/robotide/editor/texteditor.py
src/robotide/preferences/configobj.py
src/robotide/preferences/editors.py
src/robotide/preferences/settings.cfg
src/robotide/preferences/widgets.py

I've chosen to add zoom factor as a separate input in Text Editor preferences. The original issue mentioned that it should be added to font size, but I thought that would just create confusion. This way the user can be aware of its value.
I've also made the margin resizable, so that it adapts to the new font size/zoom.
The new function `build_UnaryOp` is so that configobj can handle variable from settings.cfg that have negative values. I had to fix this too because zoom factor range is [-10, 20]. 
Fixes #1298

Added zoom factor to settings.cfg so that changes persist in Text Editor

---

src/robotide/editor/kweditor.py

Fixes #2084
Issue stems from the order in which the shortcut conditions are called in kweditor.
I introduced this issue with the change to kweditor [from this PR](https://github.com/robotframework/RIDE/pull/2005/files#diff-8bdbfc0a2ddae742c87fb07ee3795b85).
Reversing those changes would have been enough, but I thought `OnKeyDown` could be improved a little with how it calls those conditions.
Please check all shortcuts to make sure I didn't break any of them.

Fixed SelectAll issue in Grid Editor

---

src/robotide/preferences/widgets.py

Uses unicode to calculate font name size when on Python 2.7

---

src/robotide/editor/kweditor.py
src/robotide/log/log.py
src/robotide/parserlog/parserlog.py

Fixes #2084
Issue stems from the order in which the shortcut conditions are called in kweditor. Additionally, there is a conflict between RIDE and Parser Log tab shortcuts.
Changes:
- improved `if` case structure in `OnKeyDown`  (functionality should be the same or better)
- made RIDE and Parser Log tabs to unregister their shortcuts when they're not selected
- updated code so that `Select All` works in RIDE and Parser Log tabs (wasn't implemented)
Please check to see that shortcuts work. On MacOS there might be some additional conflicts between shortcuts from Grid Editor and Text Editor, so make sure to check shortcuts both when Text Editor is disabled and enabled. Leave a message if you find any discrepancies.
Sorry it took so long, I've been busy with other stuff and kinda forgot.

Fixed SelectAll issue in Grid Editor, RIDE Log and Parser Log

---

src/robotide/editor/kweditor.py

I've found a way to improve the [fix for Windows 10 selection issue](https://github.com/robotframework/RIDE/issues/1739), so that it doesn't cause focus issues when F2 key is used.
Unlike the other Operating Systems, it seems that on Windows 10 grid selection breaks if `SetFocus()` is used before `SetSelection()` or `SelectAll()`. I removed `StartingClick()` because that was the main culprit behind the out of order call.
With this fix, behavior for entering edit mode will be the same for both F2 and double click (entire cell text will be selected). I will add the other enhancements we talked about for F2 with another PR.
#2135

Fixed focus issue when using F2 to edit grid cell

---

src/robotide/editor/tags.py

I also fixed 2 additional issues I found while investigating this:
- Tagbox is left empty, without being destroyed, if you empty the content of a new tag
- the following runtime error appears if you click on another tag, instead of pressing ENTER key after you delete a tag
```
Traceback (most recent call last):
File "C:\Python37\lib\site-packages\robotide\editor\tags.py", line 191, in OnKillFocus
if self.value != '':
File "C:\Python37\lib\site-packages\robotide\editor\tags.py", line 204, in value
return self.GetValue().strip()
RuntimeError: wrapped C/C++ object of type TagBox has been deleted
```
Fixes #2146

Fixed crash when you delete tag and more

---

src/robotide/editor/contentassist.py
src/robotide/editor/kweditor.py

When in Cell Editor we have selected text, it will be enclosed if pressed these keys:
'{', '[', '(', "'", "'", '`'
If no text selected writes the right symbol, or a duplicate.
If in navigation mode in Grid Editor, uses the full cell content to apply the enclosing.

Encloses text in Cell or selected text with certain symbols

---

src/robotide/contrib/testrunner/testrunnerplugin.py
src/robotide/controller/filecontrollers.py
src/robotide/controller/macrocontrollers.py
src/robotide/controller/ui/treecontroller.py
src/robotide/publish/messages.py
src/robotide/ui/treenodehandlers.py
src/robotide/ui/treeplugin.py
utest/controller/ui/test_treecontroller.py

1668: Selecting and deselecting tests using the right-click commands on the root of a deeply nested test folder, freezes RIDE for several minutes.
The problem is caused by the strategy to find the test to select/deselect: expanding and collapsing all the nodes in the Tree plugin. This causes CPU waste to expand/collapse (and maybe render) and  create the tree node handlers.
The idea of the fix is to navigate the tests using the link between controllers, in order to avoid all the dancing of the tree nodes.
To evaluate the improvement: open a large test suite. right-click on the root of the tree and "Select all tests". Click on another node of the tree. Observe the time required for the UI to return responsive. This should be noticeable even without a precise measurement. In fact, in my …

Fix for 1668: Given a large test suite, selecting all tests from the root of tree, freezes RIDE for some time

---

src/robotide/editor/clipboard.py
src/robotide/editor/kweditor.py
src/robotide/publish/messages.py
src/robotide/ui/actiontriggers.py
src/robotide/ui/mainframe.py

1. On Mac OS, copy/paste/cut not working in grid cell edit mode
2. Cannot save modifications in grid cell edit mode via shortcut ctrl/cmd + s
3. Deleting all text in grid cell edit mode not working
4. On Windows, performing menu action "cut" in grid cell edit mode will raise exception
5. Typos in actiontriggers.py

Bugs fixing on editor grid

---

src/robotide/ui/treenodehandlers.py

The _ActionHandler class is based off wx.Window which causes a native widget to be created. Avoid adding this native window to the tree to prevent Windows OS freezes when the tree is scrolled. Add it to the tree's parent instead.
Looks like the only wx.Window feature utilized is for popup menus when a tree item is right-clicked.
Attempts to fix #1843.

Update treenodehandlers.py to prevent freeze ups

---

src/robotide/editor/kweditor.py

With wxPython 4.1.0, cannot edit grid cells in windows and linux, to resolve it, I removed the useless event listener OnKillFocus.
Verified with both wxPython 4.0.7.post2 and wxPython 4.1.0

Fix cannot edit grid cell with wxPython 4.1.0

---

src/robotide/application/application.py
src/robotide/controller/project.py
src/robotide/editor/kweditor.py
src/robotide/editor/listeditor.py
src/robotide/editor/settingeditors.py
src/robotide/ui/mainframe.py
src/robotide/ui/treeplugin.py
src/robotide/utils/__init__.py
src/robotide/utils/eventhandler.py

- Directory workspace
In the following scenario will trigger reload workspace confirm dialog, when confirmed, it will reload whole workspace, otherwise, it will discard changes
1. create/modify/delete/rename files from outer editor, only works for .robot,.txt,.tsv,.resource
2. create/rename/delete sub folders
3. rename/delete workspace root folder, note: in the case, when confirmed reload, will ask user to open new directory
- Single suite file workspace
if this file is renamed/deleted, will also trigger reload workspace confirm dialog, when confirmed reload, will ask user to open new directory
Tested in windows, macOS and Ubuntu with wxPython 4.1.0.
**Looks like wx.FileSystemWatcher cannot work properly in MacOS with wxPython 4.0.7.post2**

Redesign RideEventHandler and file system monitoring feature

---

src/robotide/ui/treenodehandlers.py
src/robotide/widgets/popupmenu.py

class _ActionHandler's inheritance "wx.Window" is not necessary at all.
Remove this inheritance will fix this issue, and in the same time, it will improve the tree plugin's performance significantly

Fix win10 system freeze when loading large project

---

src/robotide/ui/fileexplorerplugin.py
src/robotide/ui/treeplugin.py

Fixed RIDE startup crash when Tree or File Explorer plugins use opened=False setting

---

src/robotide/editor/kweditor.py

In Mac OS, Grid cell will lose focus when mouse is moved out of the cell's boundary.
This will cause mouse click cannot work in content assist list.

[Mac OS] Fix: Cannot use mouse click content assist list in grid cell.

---

src/robotide/editor/contentassist.py

This commit: Disable mac os text ctrl smart input char replace
Causes a critical bug, only in *Mac OS*:
1. fixed errors raised when clicking adding library/variable/resource button
2. fixed errors raised when pressing ctrl + 1 / 2 in adding library/variable/resource  dialog file name editor text ctrl

Fix errors when adding library/resource/variables in test suite

---

src/robotide/ui/mainframe.py

This issue is not fully fixed.
Here're the test cases for this PR:
Case 1. delete config file -> launch RIDE -> double click app title, app maximize -> restart app (Only fixed this case in last PR)
Case 2. open app -> click maxmize button -> restart app (**bug fixed on MacOS**)
Case 3. open app -> click maxmize button -> restart app -> double click app title (**bug fixed on MacOS**)
Case 4. open app -> resize window -> restart app (**bug fixed on MacOS**)
Case 5. open app -> resize window -> move window position -> restart app
Case 6. open app -> resize window -> move window position -> minimize window -> restart app
Case 7. open app -> double click app title, app maximize -> minimize window -> restart app
Check app position and size are correct and no corners are hidden.
I tested in …

Fix frame size is incorrect when maximize app window

---

src/robotide/application/application.py

1. delete setting.cfg
2. launch ride
3. errors will raise because `self.workspace_path ` is None

Fix errors when app launched with param path 'None'

---

CHANGELOG.adoc
src/robotide/context/coreplugins.py
src/robotide/editor/texteditor.py
src/robotide/log/log.py
src/robotide/publish/messages.py
src/robotide/publish/publisher.py
src/robotide/ui/pluginmanager.py
utest/plugin/test_messages.py
utest/publish/test_message_publishing.py
utest/resources/fake.cfg
utest/resources/mocks.py
utest/ui/test_tree.py

- LogPlugin should be loaded in the first, because some error message could be printed in log plugin during other plugin loading
- Title in plugin manage setting page cannot show properly

Make publisher errors slient

---

CHANGELOG.adoc
src/robotide/ui/mainframe.py

Fixed RIDE cannot close properly when Screenshot library is loaded

Fixed RIDE cannot close properly when Screenshot library is loaded

---

CHANGELOG.adoc
src/robotide/__init__.py

When launching RIDE with pythonw.exe, the `sys.stdout` & `sys.stderr` will be None, and some errors may occur.
Related issue: 
https://github.com/robotframework/RIDE/issues/2319
https://github.com/robotframework/RIDE/issues/2197

Fix sys stderr is none in pythonw

---

src/robotide/publish/publisher.py

Add protection for publisher, in some cases, inspect.getmembers may raise exception

Add protection for publisher, in some cases, inspect.getmembers may raise exception

---

src/robotide/controller/project.py
src/robotide/editor/kweditor.py

1. When user have old RIDE version with config files, this will cause "auto size cols" is activated automatically.
2. Create new resource should not change the project default dir path, this will cause ${EXEC_DIR} cannot be resolved correctly.

Minor fixes

---

src/robotide/controller/macrocontrollers.py
src/robotide/editor/kweditor.py
src/robotide/editor/listeditor.py
src/robotide/ui/treeplugin.py

1. Fix publisher msg error when delete variables in tree
2. Fix publisher msg error when using DataDriver
3. Fix publisher msg error when reset grid settings

Fix some silent listener errors

---

src/robotide/spec/libraryfetcher.py
utest/resources/robotdata/libs/TestLib.py
utest/spec/test_iteminfo.py

Fix the issue (#2342) where python keyword libraries fail to load in RIDE due to named arguments. e.g.:
def kw(self, *, arg1=None):

Include kwonlyargs support

---

src/robotide/contrib/testrunner/testrunnerplugin.py

This is only for windows platform and when encoding settings are different (often the case in Western Europe)

Fix for diacritic characters display on RIDE console

---

src/robotide/ui/keywordsearch.py

The keyword search dialog, unlike the test case search dialog, did not show the number of results from the search. Now this one does as well.

Include hit count for keyword search

---

CHANGELOG.adoc
src/robotide/application/CHANGELOG.html
src/robotide/application/releasenotes.py
src/robotide/lib/robot/writer/datafilewriter.py
src/robotide/lib/robot/writer/formatters.py
src/robotide/lib/robot/writer/rowsplitter.py

Split long cols

---

src/robotide/postinstall/__init__.py

Fixed the issue of not being able to create desktop shortcut icons, successfully tested on Deepin and UOS Linux operating systems

Add Chinese language support for 'zh'

---

CONTRIBUTING.adoc

- fix an incorrect link redirect to the slack robotframework community.
- add the 'commit' command on the instruction 7 on how to contribute.

DOCS: fix inconsistent link and git command

---

src/robotide/ui/keywordsearch.py

fix:  keywords search dailog AttributeError: 'NoneType' object has no attribute 'name'
